models/action_model.py
class ActionModel:
  
  actions = [
      {'id': 1, 'name': 'Action 1'},
      {'id': 2, 'name': 'Action 2'},
      {'id': 3, 'name': 'Action 3'}
    ] 

  def GetActions(self) -> list:
    return self.actions

  def GetAction(self, action_id: int) -> dict:
    for action in self.actions:
      if action['id'] == action_id:
        return action
    
    return None 

models/user_model.py
class UserModel:
  
  users = [
      {'id': 1, 'name': 'Alice'},
      {'id': 2, 'name': 'Bob'},
      {'id': 3, 'name': 'Charlie'}
    ]

  def GetUsers(self) -> list:
    return self.users 
  
  def GetUser(self, user_id:int) -> dict:
    for user in self.users:
      if user['id'] == user_id:
        return user
    
    return None

__init__.py
from flask import Flask, render_template
from controllers.user_controller import user_bp
from controllers.action_controller import action_bp

app = Flask(__name__)
app.register_blueprint(user_bp)
app.register_blueprint(action_bp)
  
@app.route('/')
def index():
  return render_template("index.html")

if __name__ == "__main__":
  app.run(debug=True)

controllers/action_controller.py
from flask import render_template, Blueprint
from models.action_model import ActionModel

action_bp = Blueprint("action", __name__, url_prefix="/actions")

@action_bp.route('/')
def index():
  actions = ActionModel().GetActions()
  return render_template("actions/index.html", actions=actions)

@action_bp.route('/<int:action_id>/edit')
def edit(action_id:int):
  action = ActionModel().GetAction(action_id)
  return render_template("actions/edit.html", action=action)

controllers/user_controller.py
from flask import render_template, Blueprint
from models.user_model import UserModel

user_bp = Blueprint("user", __name__, url_prefix="/users")

@user_bp.route('/')
def index():
  users = UserModel().GetUsers()
  return render_template("users/index.html", users=users)

@user_bp.route('/<int:user_id>/edit')
def edit(user_id:int):
  user = UserModel().GetUser(user_id)
  return render_template("users/edit.html", user=user)

templates/actions/edit.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>MVC Pattern - Actions</title>
  </head>
  <body>
    <h1>Action Section: {{ action['name'] }}</h1>
    <h3>Details:</h3>
    <div>
      <label>Id: {{ action['id'] }}</label>
    </div>
    <div>
      <label>Name: {{ action['name'] }}</label>
    </div>
    <a href="{{ url_for('action.index') }}"><h3>Go Back</h3></a>
  </body>
</html>

templates/actions/index.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>MVC Pattern - Actions</title>
  </head>
  <body>
    <h1>Action Section</h1>
    <ul>
      {% for action in actions %}
        <a href="{{ url_for('action.edit', action_id=action['id']) }}">
          <li>{{ action["name"] }}</li>
        </a>
      {% endfor %}
    </ul>
    <span>
      <a href="{{ url_for('index') }}">
        <h3>Go Start</h3>
      </a>
    </span>
    <span>
      <a href="{{ url_for('user.index') }}">
        <h3>User Section</h3>
      </a>
    </span>
  </body>
</html>

templates/index.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>MVC Pattern</title>
  </head>
  <body>
    <h1>Hello MVC!</h1>
    <a href="{{ url_for('user.index') }}"><h3>User Section</h3></a>
    <a href="{{ url_for('action.index') }}"><h3>Action Section</h3></a>
  </body>
</html>

templates/users/edit.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>MVC Pattern - Users</title>
  </head>
  <body>
    <h1>User Section: {{ user['name'] }}</h1>
    <h3>Details:</h3>
    <div>
      <label>Id: {{ user['id'] }}</label>
    </div>
    <div>
      <label>Name: {{ user['name'] }}</label>
    </div>
    <a href="{{ url_for('user.index') }}"><h3>Go Back</h3></a>
  </body>
</html>

templates/users/index.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>MVC Pattern - Users</title>
  </head>
  <body>
    <h1>User Section</h1>
    <ul>
      {% for user in users %}
        <a href="{{ url_for('user.edit', user_id=user['id']) }}">
          <li>{{ user["name"] }}</li>
        </a>
      {% endfor %}
    </ul>
    <span>
      <a href="{{ url_for('index') }}">
        <h3>Go Start</h3>
      </a>
    </span>
    <span>
      <a href="{{ url_for('action.index') }}">
        <h3>Action Section</h3>
      </a>
    </span>
  </body>
</html>